language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

sudo: false

install:
  - phpunit --version
  - composer install --no-interaction

script:
  - phpunit --stop-on-failure

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
  - phpunit --testdox